<<<<<<< HEAD

name: QA Automation CI

on: [push, pull_request]

jobs:
  test:
=======
name: QA Automation - Mobile Challenge

on:
  push:
    branches: [ "main", "master" ]
  pull_request:

jobs:
  tests:
>>>>>>> 5c0c1a34233fcae625a4de36fed2127ff8cfe9e5
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Executar testes
<<<<<<< HEAD
        run: npm run test:ci

      - name: Upload Extent Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-report
          path: reports/extent
=======
        run: npm test
>>>>>>> 5c0c1a34233fcae625a4de36fed2127ff8cfe9e5
